<a href="https://colab.research.google.com/github/Sankar-A06/pythonprogramming/blob/main/Copy_of_Assessment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Assignment 1
1.Peform arithemetic operation on NumPy arrays.

In [ ]:
import numpy as np
a = np.array([[2,4,6], [8,10,12],[14,16,18]])# ,dtype=np.float64)
b = np.array([[1,2,3],[4,5,6],[7,8,9]])#, dtype=np.float64)
#Elementwise addition
#print(a+b)
print(np.add(a,b))
#ElementWise subtraction
#print(a-b)
print(np.subtract(a,b))
#Elementwise multiplication
#print(a*b)
print(np.multiply(a,b))
#Elemmentary Division
#print(a/b)
print(np.divide(a,b))
#Elementary power
#print(a**b)
print(np.power(a,b))
#Each element  in an array divides its corresponding element in another array and get remainder mod() or remainder() functions
#print(a%b)
print(np.mod(a,b))
#Elementary division and get corresponding quiotent
#print(a//b)
print(np.divmod(a,b))
#Each element got a positive value
print(np.abs(a))
print(np.abs(b))
#Broadcasting
#arithmetic operations on scalar by broadcasting
print(a+2)

[[ 3  6  9]
 [12 15 18]
 [21 24 27]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[  2   8  18]
 [ 32  50  72]
 [ 98 128 162]]
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]
[[           2           16          216]
 [        4096       100000      2985984]
 [   105413504   4294967296 198359290368]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
(array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]]), array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]]))
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 4  6  8]
 [10 12 14]
 [16 18 20]]


2.Write a Script to compute the mean and standard deviation of a Numpy Array.

Mean = sum_of_obesrvations/number_of_observations.

standard_deviation=sqrtof(xi-mean)^2/N.

In [ ]:
array = np.array([1,2,3,4,5,6,7,8,9,10])
def mean(arr):
  return np.mean(arr)
def st_dev(arr):
  return np.std(arr)
print("Mean ",mean(array))
print("Standard Deviation ",st_dev(array))


Mean  5.5
Standard Deviation  2.8722813232690143


3.Create a NumPy array of integers from 10 to 50 with a step size of 5.

In [ ]:

x = np.arange(10,55,5)
print(x)
#or
a=[]
for i in range(10,55,5):
  a.append(i)
print(a)

[10 15 20 25 30 35 40 45 50]
[10, 15, 20, 25, 30, 35, 40, 45, 50]


4.Reshape the array into a 2x4 matrix

In [ ]:
x = np.arange(10,50,5)#first it is a 1x8 matrix
print(np.shape(x))
print(x)
print(x.reshape(2,4))#reshape into 2x4 matrix
print(x.reshape(2,4).shape)



(8,)
[10 15 20 25 30 35 40 45]
[[10 15 20 25]
 [30 35 40 45]]
(2, 4)


5.Given the array arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]):

i)	Extract the sub-matrix containing the last two rows and first two columns.




In [ ]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a[1:3,0:2])

[[4 5]
 [7 8]]


ii)	Replace all elements greater than 4 with 0.

In [ ]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a[a>4])
a[a>4]=0
print(a)

[5 6 7 8 9]
[[2 3 4]
 [4 0 0]
 [0 0 0]]


5.Given the array arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]):

•	Extract the sub-matrix containing the last two rows and first two columns.

•	Replace all elements greater than 4 with 0.


In [ ]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
array = a[1:,:2]
array[array[array>4]]=0
print(array)


[[4 0]
 [0 0]]


6.Create two 1D arrays:

•	a = np.array([1, 2, 3])

•	b = np.array([4, 5, 6])

•	Perform element-wise addition, multiplication, and division.


In [ ]:
a = np.array([1, 2, 3])

b = np.array([4, 5, 6])
print(a+b)
print(a*b)
print(a/b)

[5 7 9]
[ 4 10 18]
[0.25 0.4  0.5 ]


7.Create a random NumPy array of size (4, 4). Compute:

•	Mean of each column.

•	Maximum value of the entire array.

•	Sum of all elements.


In [ ]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
for i in range(4):
  print(np.mean(arr[:,i:i+1]))
print(np.max(arr))
print(np.sum(arr))


7.0
8.0
9.0
10.0
16
136


8.Given the array arr = np.array([1, 2, 3, 4]), add 10 to each element and

multiply the result by 2.

In [ ]:
arr = np.array([1,2,3,4])
a = arr+10
print(np.sum(a)*2)

100


9.Perform advanced slicing and indexing on a 3D array.

Create a 3D NumPy array arr of shape (3, 4, 5) with random integers

ranging from 1 to 100. Perform the following:

•	Extract the second "layer" (i.e., the second 2D array) in the first

dimension. • Extract the first two rows and the last three columns from

each "layer."

•	Replace all elements divisible by 3 with -1.


In [ ]:
a = np.random.randint(1,101,size=(3,4,5))#Here is the 3D array with shape(3,4,5) with random integers ranging from 1 to 100
#Here  I Extract the second layer (i.e., the second 2D array) in the first dimension.
print(a)
print()
print(a[1:2,:,:])
print()
#Extract the first two rows and the last three columns from each layer or first dimension.
print("Here I Extract the first two rows and the last three columns from each layer or first dimension.")
print(a[:,:2,-3:])
print()
a[a%3==0]=-1
print(a)# Replace all elements divisible by 3 with -1

[[[ 68   5  33  10  54]
  [ 40   2  78  80  10]
  [ 41  65  94  71 100]
  [ 46  65  16  16  58]]

 [[ 21  83  60  58  94]
  [ 72  86   6  31  77]
  [ 61 100  97  70  87]
  [ 67  21  42  12  34]]

 [[ 51  12  67  25   3]
  [  4  29  16  15  90]
  [ 52  52   5  45  14]
  [ 90  33   7  83   2]]]

[[[ 21  83  60  58  94]
  [ 72  86   6  31  77]
  [ 61 100  97  70  87]
  [ 67  21  42  12  34]]]

Here I Extract the first two rows and the last three columns from each layer or first dimension.
[[[33 10 54]
  [78 80 10]]

 [[60 58 94]
  [ 6 31 77]]

 [[67 25  3]
  [16 15 90]]]

[[[ 68   5  -1  10  -1]
  [ 40   2  -1  80  10]
  [ 41  65  94  71 100]
  [ 46  65  16  16  58]]

 [[ -1  83  -1  58  94]
  [ -1  86  -1  31  77]
  [ 61 100  97  70  -1]
  [ 67  -1  -1  -1  34]]

 [[ -1  -1  67  25  -1]
  [  4  29  16  -1  -1]
  [ 52  52   5  -1  14]
  [ -1  -1   7  83   2]]]


10.Work with broadcasting and advanced operations in NumPy.

Create a NumPy array arr of shape (3, 3) with random integers

between 1 and 20. Perform the following:

•	Subtract the mean of each row from its respective elements

 (row-wise normalization).

•	Create a new array by squaring all the elements in arr.

•	Find the indices of the top 3 maximum values in the entire array.


In [ ]:

arr = np.random.randint(1, 21, size=(3, 3))# Create a NumPy array arr of shape (3, 3) with random integers between 1 and 20.
row_means = np.mean(arr, axis=1, keepdims=True)# Subtract the mean of each row from its respective elements (row-wise normalization).
normalized_arr = arr - row_means # Create a new array by squaring all the elements in arr.
squared_arr = np.square(arr)
# Find the indices of the top 3 maximum values in the entire array.
# Find the top 3 values and their indices
flat_arr = arr.ravel()  # Flatten the array for easier sorting
sorted_indices = np.argsort(flat_arr)[-3:]  # Indices of the top 3 values in the flattened array
highest_indices = [np.unravel_index(idx, arr.shape) for idx in sorted_indices] # Convert to 2D indices
highest_values= [flat_arr[idx] for idx in sorted_indices]  # Retrieve the values
print(arr)
print(normalized_arr)
print(squared_arr)
for value, index in zip(highest_values,highest_indices):
    print("Value:",value, "at Index: ",index)

[[20 13 16]
 [ 2 16  2]
 [13 17 14]]
[[ 3.66666667 -3.33333333 -0.33333333]
 [-4.66666667  9.33333333 -4.66666667]
 [-1.66666667  2.33333333 -0.66666667]]
[[400 169 256]
 [  4 256   4]
 [169 289 196]]
Value: 16 at Index:  (1, 1)
Value: 17 at Index:  (2, 1)
Value: 20 at Index:  (0, 0)
